version: "3"

#networks:
 # public: {}

services:
#  prometheus:
   scraper:
    image: prom/prometheus:latest
    volumes:
#     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
     - ./prometheus:/etc/prometheus
#      - ./prometheus_db:/var/lib/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    restart: unless-stopped
    ports:
      - '9090:9090'
    
 # grafana:
   viewer:
    image: grafana/grafana
    user: "1000" #? 104
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secure_pass
    volumes:
 #     - ./grafana_db:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - scraper
    ports:
      - '3000:3000'
    
   exposer:
  #for test use image local:exposer
    #image: expose:latest
    build: exposer/
    ports:
      - 8000:8000