{
 "title": "Exposer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "eBay Chalenge Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count_total" }
   ]
  },
  {
   "title": "eBay Chalenge Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gauge{resource_type=\"METRIC\"}"
    }
   ]
  },
  {
   "title": "eBay chalenge histogramm",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "histogram_sum" }
   ]
  }
 ]
}