version: "3"

#networks:
 # public: {}

services:
#  prometheus:
   scraper:
    image: prom/prometheus:latest
    volumes:
#     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/etc/prometheus
#      - ./prometheus/targets:/etc/prometheus/targets
     
#      - ./prometheus_db:/var/lib/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'

    restart: unless-stopped
    ports:
      - $SCRAPER_PORT:$SCRAPER_PORT
 #     - 9090:9090
    
 # grafana:
   viewer:
    image: grafana/grafana
    user: "1000" #? 104
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secure_pass
    volumes:
 #     - ./grafana_db:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
#      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning:/etc/grafana/provisioning
#      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - scraper
    ports:
      - $VIEWER_PORT:$VIEWER_PORT
    
   exposer:
    #image: expose:latest
    build: exposer/
    environment:
        - EXPOSER=$EXPOSER_PORT   
    ports:
      - $EXPOSER_PORT:$EXPOSER_PORT