global:
  scrape_interval: 5s
  external_labels:
    monitor: 'ebay_chalenge'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['localhost:9090']
  - job_name: 'exposer' 
    static_configs: 
      - targets: ['exposer:8000']