<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:tns="http://service.stockquote.jaxws.company.com/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	targetNamespace="http://service.stockquote.jaxws.company.com/" 
	name="StockQuoteService">
  <types>
    <xsd:schema>
      <xsd:import schemaLocation="StockQuoteService.xsd" namespace="http://service.stockquote.jaxws.company.com/"></xsd:import>
    </xsd:schema>
  </types>
  <message name="getQuote">
    <part element="tns:getQuote" name="parameters"></part>
  </message>
  <message name="getQuoteResponse">
    <part element="tns:getQuoteResponse" name="parameters"></part>
  </message>
  <portType name="StockQuote">
    <operation name="getQuote">
      <input message="tns:getQuote"></input>
      <output message="tns:getQuoteResponse"></output>
    </operation>
  </portType>
  <binding name="StockQuotePortBinding" type="tns:StockQuote">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"></soap:binding>
    <operation name="getQuote">
      <soap:operation soapAction=""></soap:operation>
      <input>
        <soap:body use="literal"></soap:body>
      </input>
      <output>
        <soap:body use="literal"></soap:body>
      </output>
    </operation>
  </binding>
  <service name="StockQuoteService">
    <port name="StockQuotePort" binding="tns:StockQuotePortBinding">
      <soap:address location="http://localhost:1970/StockQuote/StockQuoteService"></soap:address>
    </port>
  </service>
</definitions>